/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'page-templates': PageTemplate;
    posts: Post;
    products: Product;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'page-templates': PageTemplatesSelect<false> | PageTemplatesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'marketing' | 'platform' | 'pilot' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'video';
    prefix?: string | null;
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Wrap words in **double asterisks** to emphasise them (Pilot hero only).
     */
    subtitle?: string | null;
    illustration?: (number | null) | Media;
    background?: (number | null) | Media;
    headlineSuffix?: string | null;
    /**
     * The strip loops seamlessly — you only need to enter each item once.
     */
    tickerItems?:
      | {
          text: string;
          accent?: boolean | null;
          liveDot?: boolean | null;
          id?: string | null;
        }[]
      | null;
    trustLabel?: string | null;
    trustItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pilotConsole?: {
      label?: string | null;
      meta?: string | null;
      footerLeft?: string | null;
      footerRight?: string | null;
      /**
       * These cycle through the console as a live feed, oldest scrolling off.
       */
      logs?:
        | {
            time?: string | null;
            tag: string;
            tone?: ('validate' | 'dispatch' | 'execute' | 'close') | null;
            value?: string | null;
            message: string;
            id?: string | null;
          }[]
        | null;
    };
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
            rounded?: ('none' | 'md' | 'full') | null;
            /**
             * Hex. Leave blank for the style default.
             */
            borderColor?: string | null;
            /**
             * Hex. Leave blank for the style default.
             */
            textColor?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    /**
     * Autoplaying, muted, looping background video for the hero.
     */
    backgroundVideo?: (number | null) | Media;
  };
  layout?:
    | (
        | HeaderBlock
        | FooterBlock
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | LogoMarqueeBlock
        | TextVideoBlock
        | FeatureTabsBlock
        | CtaBannerBlock
        | UpdatesCardsBlock
        | SpotlightBlock
        | StatsBannerBlock
        | TestimonialCardsBlock
        | DifferentiatorsBlock
        | DiagramSectionBlock
        | ResourceHubBlock
        | PlatformCarouselBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Skip the header entirely. Ignored if a Header block is in the layout.
   */
  hideHeader?: boolean | null;
  /**
   * Skip the footer entirely. Ignored if a Footer block is in the layout.
   */
  hideFooter?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  template?: {
    /**
     * Optionally base this page on a reusable template.
     */
    templateRef?: (number | null) | PageTemplate;
    /**
     * On: this page always renders the template's current blocks instead of its own. Off: use the button below to copy the template's blocks in once, then edit them independently.
     */
    syncWithTemplate?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Used to generate the URL slug and shown in the admin list — not displayed on the page itself. Build the visible page from the blocks below.
   */
  title: string;
  layout?:
    | (
        | HeaderBlock
        | FooterBlock
        | BreadcrumbBlock
        | HeroSectionBlock
        | AnnouncementBannerBlock
        | SectionHeadingBlock
        | FeatureChecklistBlock
        | TrustBadgesBlock
        | SpecsTableBlock
        | IntegrationsListBlock
        | ContentBlock
        | MediaBlock
        | CallToActionBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Skip the header entirely. Ignored if a Header block is in the layout.
   */
  hideHeader?: boolean | null;
  /**
   * Skip the footer entirely. Ignored if a Footer block is in the layout.
   */
  hideFooter?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock".
 */
export interface HeaderBlock {
  /**
   * Always renders at the very top of the page, above the hero, no matter where you place this block in the list. Adding it replaces the default header for this page.
   */
  variant?: ('default' | 'glass') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'headerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock".
 */
export interface FooterBlock {
  /**
   * Always renders at the very bottom of the page, no matter where you place this block in the list. Adding it replaces the default footer for this page.
   */
  variant?: ('default' | 'glass') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BreadcrumbBlock".
 */
export interface BreadcrumbBlock {
  /**
   * Shown as the last segment: Home / Products / <this>.
   */
  label: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'breadcrumb';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionBlock".
 */
export interface HeroSectionBlock {
  type: 'video' | 'gradient' | 'split' | 'none';
  /**
   * For "Background": full-bleed behind the content. For "Image left": shown in the left column. Accepts an image or a video file.
   */
  media?: (number | null) | Media;
  /**
   * 0 = left to right, 90 = bottom to top, 180 = right to left.
   */
  gradientAngle?: number | null;
  /**
   * At least 2 stops, in order. Hex values.
   */
  gradientColors?:
    | {
        color: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A decorative graphic (e.g. grid lines) blended into the top half of the hero. For "Background" types it overlays the top of the media; for "Image left" it sits below the right-side content.
   */
  blendImage?: (number | null) | Media;
  /**
   * Heading, sub text, a checklist, or CTA buttons — add as many as you need.
   */
  content?: (StyledTextBlock | FeatureChecklistBlock | CallToActionBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StyledTextBlock".
 */
export interface StyledTextBlock {
  text: string;
  fontSize?: ('sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl') | null;
  fontFamily?: ('sans' | 'serif' | 'mono') | null;
  bold?: boolean | null;
  /**
   * Hex color. Leave blank to inherit.
   */
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'styledText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureChecklistBlock".
 */
export interface FeatureChecklistBlock {
  heading?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureChecklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'active') | null;
          rounded?: ('none' | 'md' | 'full') | null;
          /**
           * Hex. Leave blank for the style default.
           */
          borderColor?: string | null;
          /**
           * Hex. Leave blank for the style default.
           */
          textColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementBannerBlock".
 */
export interface AnnouncementBannerBlock {
  heading: string;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'announcementBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock".
 */
export interface SectionHeadingBlock {
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  alignment: 'left' | 'center' | 'right';
  size: 'small' | 'medium' | 'large' | 'xlarge';
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesBlock".
 */
export interface TrustBadgesBlock {
  heading?: string | null;
  badges?:
    | {
        logo: number | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustBadges';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecsTableBlock".
 */
export interface SpecsTableBlock {
  heading?: string | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'specsTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsListBlock".
 */
export interface IntegrationsListBlock {
  heading?: string | null;
  integrations?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integrationsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          rounded?: ('none' | 'md' | 'full') | null;
          /**
           * Hex. Leave blank for the style default.
           */
          borderColor?: string | null;
          /**
           * Hex. Leave blank for the style default.
           */
          textColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoMarqueeBlock".
 */
export interface LogoMarqueeBlock {
  /**
   * Optional. Leave empty to hide the coloured heading bar.
   */
  heading?: string | null;
  speed?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
  spacing?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
  size?: ('1' | '2' | '3' | '4' | '5' | '6' | '7') | null;
  bordered?: boolean | null;
  /**
   * Upload each client logo. They scroll automatically.
   */
  logos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextVideoBlock".
 */
export interface TextVideoBlock {
  sectionHeading?: string | null;
  sectionSubheading?: string | null;
  /**
   * Dark theme uses light text, a gradient heading and a moving network graphic on the right.
   */
  theme?: ('light' | 'dark') | null;
  mediaPosition?: ('right' | 'left') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  linkStyle?: ('button' | 'underline') | null;
  logo?: (number | null) | Media;
  /**
   * Paste a YouTube / Wistia / Vimeo embed URL (used if no file uploaded).
   */
  videoEmbedUrl?: string | null;
  videoFile?: (number | null) | Media;
  /**
   * Pick a light color for the Light theme, or a dark color for the Dark theme.
   */
  background?: ('lightBlue' | 'white' | 'darkGradient' | 'darkNavy' | 'black') | null;
  /**
   * Shown centered below the section, e.g. "View More Success Stories".
   */
  bottomLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureTabsBlock".
 */
export interface FeatureTabsBlock {
  /**
   * Dark theme uses the glass tab bar, gradient heading and a glowing dark card (like "See FarEye AI in Action").
   */
  theme?: ('light' | 'dark') | null;
  eyebrow?: string | null;
  /**
   * Controls the left spacing of bullet lists in the dark card.
   */
  listIndent?: ('flush' | 'small' | 'medium') | null;
  heading?: string | null;
  tabs?:
    | {
        label: string;
        subheading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        stats?:
          | {
              name?: string | null;
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        linkLabel?: string | null;
        linkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  heading: string;
  subheading?: string | null;
  buttons?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'active') | null;
          rounded?: ('none' | 'md' | 'full') | null;
          /**
           * Hex. Leave blank for the style default.
           */
          borderColor?: string | null;
          /**
           * Hex. Leave blank for the style default.
           */
          textColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Falls back to a plain pink background if empty.
   */
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpdatesCardsBlock".
 */
export interface UpdatesCardsBlock {
  heading?: string | null;
  cards?:
    | {
        image?: (number | null) | Media;
        /**
         * When present the image is dimmed. Tick "Coral" to colour a line.
         */
        overlayLines?:
          | {
              text: string;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        badgeType?: string | null;
        badgeCategory?: string | null;
        title?: string | null;
        action?: ('download' | 'watch') | null;
        /**
         * Optional. Defaults to "Download" / "Watch".
         */
        actionLabel?: string | null;
        downloadUrl?: string | null;
        /**
         * YouTube / Wistia / Vimeo embed URL.
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'updatesCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpotlightBlock".
 */
export interface SpotlightBlock {
  heading?: string | null;
  subheading?: string | null;
  background?: ('lightBlue' | 'white' | 'pink' | 'grey') | null;
  cardType?: ('structured' | 'image') | null;
  cards?:
    | {
        /**
         * Upload OR paste an image URL below.
         */
        image?: (number | null) | Media;
        imageUrl?: string | null;
        logo?: (number | null) | Media;
        date?: string | null;
        title?: string | null;
        excerpt?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  seeAllLabel?: string | null;
  seeAllUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spotlight';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBannerBlock".
 */
export interface StatsBannerBlock {
  heading: string;
  subheading?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'active') | null;
          rounded?: ('none' | 'md' | 'full') | null;
          /**
           * Hex. Leave blank for the style default.
           */
          borderColor?: string | null;
          /**
           * Hex. Leave blank for the style default.
           */
          textColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  background?: ('white' | 'lightBlue' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialCardsBlock".
 */
export interface TestimonialCardsBlock {
  heading?: string | null;
  subheading?: string | null;
  cards?:
    | {
        logo?: (number | null) | Media;
        quote?: string | null;
        author?: string | null;
        metricValue?: string | null;
        metricLabel?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DifferentiatorsBlock".
 */
export interface DifferentiatorsBlock {
  /**
   * Dark theme shows a network background, a clickable accordion on the left and a swapping image on the right (like "What sets FarEye Apart?").
   */
  theme?: ('light' | 'dark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  illustration?: (number | null) | Media;
  cards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'differentiators';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DiagramSectionBlock".
 */
export interface DiagramSectionBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  image?: (number | null) | Media;
  /**
   * Used if no image is uploaded above.
   */
  imageUrl?: string | null;
  background?: ('white' | 'lightBlue' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'diagramSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceHubBlock".
 */
export interface ResourceHubBlock {
  eyebrow?: string | null;
  heading?: string | null;
  background?: ('darkGradient' | 'darkNavy' | 'black') | null;
  featuredCards?:
    | {
        image?: (number | null) | Media;
        imageUrl?: string | null;
        title: string;
        body?: string | null;
        action?: ('watch' | 'read' | 'none') | null;
        actionLabel?: string | null;
        videoUrl?: string | null;
        linkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  sideCards?:
    | {
        image?: (number | null) | Media;
        imageUrl?: string | null;
        title: string;
        body?: string | null;
        action?: ('watch' | 'read' | 'none') | null;
        actionLabel?: string | null;
        videoUrl?: string | null;
        linkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'resourceHub';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformCarouselBlock".
 */
export interface PlatformCarouselBlock {
  autoplaySeconds?: number | null;
  slides?:
    | {
        type: 'stats' | 'testimonial' | 'logos' | 'image';
        indicatorLogo?: (number | null) | Media;
        heading?: string | null;
        body?: string | null;
        subheading?: string | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        backgroundImage?: (number | null) | Media;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        gridHeading?: string | null;
        gridHighlight?: string | null;
        logos?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        company?: string | null;
        quote?: string | null;
        authorName?: string | null;
        authorTitle?: string | null;
        metricValue?: string | null;
        metricLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'platformCarousel';
}
/**
 * Reusable block layouts that pages can copy from or stay synced with.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates".
 */
export interface PageTemplate {
  id: number;
  name: string;
  layout?:
    | (
        | HeaderBlock
        | FooterBlock
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | LogoMarqueeBlock
        | TextVideoBlock
        | FeatureTabsBlock
        | CtaBannerBlock
        | UpdatesCardsBlock
        | SpotlightBlock
        | StatsBannerBlock
        | TestimonialCardsBlock
        | DifferentiatorsBlock
        | DiagramSectionBlock
        | ResourceHubBlock
        | PlatformCarouselBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'page-templates';
        value: number | PageTemplate;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        prefix?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subtitle?: T;
        illustration?: T;
        background?: T;
        headlineSuffix?: T;
        tickerItems?:
          | T
          | {
              text?: T;
              accent?: T;
              liveDot?: T;
              id?: T;
            };
        trustLabel?: T;
        trustItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pilotConsole?:
          | T
          | {
              label?: T;
              meta?: T;
              footerLeft?: T;
              footerRight?: T;
              logs?:
                | T
                | {
                    time?: T;
                    tag?: T;
                    tone?: T;
                    value?: T;
                    message?: T;
                    id?: T;
                  };
            };
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                    rounded?: T;
                    borderColor?: T;
                    textColor?: T;
                  };
              id?: T;
            };
        media?: T;
        backgroundVideo?: T;
      };
  layout?:
    | T
    | {
        headerBlock?: T | HeaderBlockSelect<T>;
        footerBlock?: T | FooterBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        logoMarquee?: T | LogoMarqueeBlockSelect<T>;
        textVideo?: T | TextVideoBlockSelect<T>;
        featureTabs?: T | FeatureTabsBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        updatesCards?: T | UpdatesCardsBlockSelect<T>;
        spotlight?: T | SpotlightBlockSelect<T>;
        statsBanner?: T | StatsBannerBlockSelect<T>;
        testimonialCards?: T | TestimonialCardsBlockSelect<T>;
        differentiators?: T | DifferentiatorsBlockSelect<T>;
        diagramSection?: T | DiagramSectionBlockSelect<T>;
        resourceHub?: T | ResourceHubBlockSelect<T>;
        platformCarousel?: T | PlatformCarouselBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  hideHeader?: T;
  hideFooter?: T;
  generateSlug?: T;
  slug?: T;
  template?:
    | T
    | {
        templateRef?: T;
        syncWithTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock_select".
 */
export interface HeaderBlockSelect<T extends boolean = true> {
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock_select".
 */
export interface FooterBlockSelect<T extends boolean = true> {
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              rounded?: T;
              borderColor?: T;
              textColor?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              rounded?: T;
              borderColor?: T;
              textColor?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoMarqueeBlock_select".
 */
export interface LogoMarqueeBlockSelect<T extends boolean = true> {
  heading?: T;
  speed?: T;
  spacing?: T;
  size?: T;
  bordered?: T;
  logos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextVideoBlock_select".
 */
export interface TextVideoBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  sectionSubheading?: T;
  theme?: T;
  mediaPosition?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  linkStyle?: T;
  logo?: T;
  videoEmbedUrl?: T;
  videoFile?: T;
  background?: T;
  bottomLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureTabsBlock_select".
 */
export interface FeatureTabsBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  listIndent?: T;
  heading?: T;
  tabs?:
    | T
    | {
        label?: T;
        subheading?: T;
        body?: T;
        stats?:
          | T
          | {
              name?: T;
              value?: T;
              label?: T;
              id?: T;
            };
        image?: T;
        linkLabel?: T;
        linkUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              rounded?: T;
              borderColor?: T;
              textColor?: T;
            };
        id?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpdatesCardsBlock_select".
 */
export interface UpdatesCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        image?: T;
        overlayLines?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        badgeType?: T;
        badgeCategory?: T;
        title?: T;
        action?: T;
        actionLabel?: T;
        downloadUrl?: T;
        videoUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpotlightBlock_select".
 */
export interface SpotlightBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  background?: T;
  cardType?: T;
  cards?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        logo?: T;
        date?: T;
        title?: T;
        excerpt?: T;
        url?: T;
        id?: T;
      };
  seeAllLabel?: T;
  seeAllUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBannerBlock_select".
 */
export interface StatsBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              rounded?: T;
              borderColor?: T;
              textColor?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialCardsBlock_select".
 */
export interface TestimonialCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  cards?:
    | T
    | {
        logo?: T;
        quote?: T;
        author?: T;
        metricValue?: T;
        metricLabel?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DifferentiatorsBlock_select".
 */
export interface DifferentiatorsBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  illustration?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DiagramSectionBlock_select".
 */
export interface DiagramSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  image?: T;
  imageUrl?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceHubBlock_select".
 */
export interface ResourceHubBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  background?: T;
  featuredCards?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        title?: T;
        body?: T;
        action?: T;
        actionLabel?: T;
        videoUrl?: T;
        linkUrl?: T;
        id?: T;
      };
  sideCards?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        title?: T;
        body?: T;
        action?: T;
        actionLabel?: T;
        videoUrl?: T;
        linkUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformCarouselBlock_select".
 */
export interface PlatformCarouselBlockSelect<T extends boolean = true> {
  autoplaySeconds?: T;
  slides?:
    | T
    | {
        type?: T;
        indicatorLogo?: T;
        heading?: T;
        body?: T;
        subheading?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        backgroundImage?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        gridHeading?: T;
        gridHighlight?: T;
        logos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        image?: T;
        company?: T;
        quote?: T;
        authorName?: T;
        authorTitle?: T;
        metricValue?: T;
        metricLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates_select".
 */
export interface PageTemplatesSelect<T extends boolean = true> {
  name?: T;
  layout?:
    | T
    | {
        headerBlock?: T | HeaderBlockSelect<T>;
        footerBlock?: T | FooterBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        logoMarquee?: T | LogoMarqueeBlockSelect<T>;
        textVideo?: T | TextVideoBlockSelect<T>;
        featureTabs?: T | FeatureTabsBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        updatesCards?: T | UpdatesCardsBlockSelect<T>;
        spotlight?: T | SpotlightBlockSelect<T>;
        statsBanner?: T | StatsBannerBlockSelect<T>;
        testimonialCards?: T | TestimonialCardsBlockSelect<T>;
        differentiators?: T | DifferentiatorsBlockSelect<T>;
        diagramSection?: T | DiagramSectionBlockSelect<T>;
        resourceHub?: T | ResourceHubBlockSelect<T>;
        platformCarousel?: T | PlatformCarouselBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        headerBlock?: T | HeaderBlockSelect<T>;
        footerBlock?: T | FooterBlockSelect<T>;
        breadcrumb?: T | BreadcrumbBlockSelect<T>;
        heroSection?: T | HeroSectionBlockSelect<T>;
        announcementBanner?: T | AnnouncementBannerBlockSelect<T>;
        sectionHeading?: T | SectionHeadingBlockSelect<T>;
        featureChecklist?: T | FeatureChecklistBlockSelect<T>;
        trustBadges?: T | TrustBadgesBlockSelect<T>;
        specsTable?: T | SpecsTableBlockSelect<T>;
        integrationsList?: T | IntegrationsListBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  hideHeader?: T;
  hideFooter?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BreadcrumbBlock_select".
 */
export interface BreadcrumbBlockSelect<T extends boolean = true> {
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionBlock_select".
 */
export interface HeroSectionBlockSelect<T extends boolean = true> {
  type?: T;
  media?: T;
  gradientAngle?: T;
  gradientColors?:
    | T
    | {
        color?: T;
        id?: T;
      };
  blendImage?: T;
  content?:
    | T
    | {
        styledText?: T | StyledTextBlockSelect<T>;
        featureChecklist?: T | FeatureChecklistBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StyledTextBlock_select".
 */
export interface StyledTextBlockSelect<T extends boolean = true> {
  text?: T;
  fontSize?: T;
  fontFamily?: T;
  bold?: T;
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureChecklistBlock_select".
 */
export interface FeatureChecklistBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementBannerBlock_select".
 */
export interface AnnouncementBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock_select".
 */
export interface SectionHeadingBlockSelect<T extends boolean = true> {
  text?: T;
  alignment?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesBlock_select".
 */
export interface TrustBadgesBlockSelect<T extends boolean = true> {
  heading?: T;
  badges?:
    | T
    | {
        logo?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpecsTableBlock_select".
 */
export interface SpecsTableBlockSelect<T extends boolean = true> {
  heading?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsListBlock_select".
 */
export interface IntegrationsListBlockSelect<T extends boolean = true> {
  heading?: T;
  integrations?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: {
    image?: (number | null) | Media;
    /**
     * Shown when no logo image is set.
     */
    text?: string | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Add sub-links to turn this into a dropdown.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: number | Product;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    enabled?: boolean | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'products';
            value: number | Product;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer uses light text, so pick a dark shade.
   */
  backgroundColor?: ('navy' | 'teal' | 'black' | 'blue' | 'plum') | null;
  logo?: {
    image?: (number | null) | Media;
    text?: string | null;
  };
  ctaLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: number | Product;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  subscribe?: {
    heading?: string | null;
    placeholder?: string | null;
    consentText?: string | null;
    privacyLink?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'products';
            value: number | Product;
          } | null);
      url?: string | null;
      label?: string | null;
    };
    buttonLabel?: string | null;
  };
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  social?: {
    linkedin?: string | null;
    twitter?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  copyrightText?: string | null;
  rightsText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        image?: T;
        text?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        enabled?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  backgroundColor?: T;
  logo?:
    | T
    | {
        image?: T;
        text?: T;
      };
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  subscribe?:
    | T
    | {
        heading?: T;
        placeholder?: T;
        consentText?: T;
        privacyLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        buttonLabel?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        facebook?: T;
        youtube?: T;
      };
  copyrightText?: T;
  rightsText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}